- hosts: local
  become: true
  vars:
    users:
      - username: "filecoin"
  tasks:
    - name: "添加授权文件吧"
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', 'publicKey/CZchainNode.key.pub') }}"
      with_items: "{{ users }}"
