- hosts: "newMachine"
  become: true
  vars:
    users:
      - username: "filecoin"
      - username: "tianru"

  tasks:
    - name: "创建账户"
      user:
        name: "{{ item.username }}"
      with_items: "{{ users }}"


    - name: "添加授权文件"
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', 'publicKey/'+ item.username + '.key.pub') }}"
      with_items: "{{ users }}"


    - name: "修改/etc/sudoers 可写"
      shell: "chmod +w /etc/sudoers"


    - name: "授权用户为无密码sudo用户"
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
      with_items: "{{ users }}"

    - name: "修改/etc/sudoers 不可写"
      shell: "chmod -w /etc/sudoers"
