- name: window2加入集群
  shell: export FULLNODE_API_INFO\={{ fullnode2_link }} ; export TRUST_PARAMS=1; ~/bin/lotus-window init --actor {{ minerID }} > ~/masterinit.log
  register: window2_result
  when: host == "window2"

- name: poster加入集群
  shell: export FULLNODE_API_INFO\={{ fullnode2_link }} ; export TRUST_PARAMS=1;~/bin/lotus-poster init --actor {{ minerID }} > ~/masterinit.log
  when: host == "window2"

- name: window重启
  shell: export FULLNODE_API_INFO\={{ fullnode2_link }} ; ~/bin/view_lotus.sh window
  when: host == "window2"

- name: poster重启
  shell: export FULLNODE_API_INFO\={{ fullnode2_link }} ; ~/bin/view_lotus.sh poster
  when: host == "window2"

- name: window2_link
  shell: export FULLNODE_API_INFO\={{ fullnode1_link }} ; ~/bin/lotus-window auth api-info --perm admin |awk -F "=" '{print $2}'
  register: window2_link
  when: host == "window2"

- name: window2-peersID
  shell: ~/bin/view_lotus.sh id |grep lotus-window -A 1|awk "NR==2{print}"
  register: window2_peersID
  when: host == "window2"

- name: window2-posterID
  shell: ~/bin/view_lotus.sh id |grep lotus-poster -A 1|awk "NR==2{print}"|awk -F "/" '{print $7}'
  register: window2_posterID
  when: host == "window2"

- name: 下载存储集群文件到本地
  shell: wget -O ~/.lotusposter/{{ item.file }} http://10.10.8.107/get/script_file/{{ item.poster_file }}
  with_items:
    - { poster_file: "poster_group_2_c.toml", file: "c.toml" }
    - { poster_file: "poster_group_2_s.json", file: "s.json" }
  when: host == "window2"

- name: 写入变量文件
  remote_user: "{{ sourceUser }}"
  ignore_errors: True
  become: yes
  become_user: "{{ sourceUser }}"
  shell: "echo {{ item.export}}: {{ item.wallet }} >> /home/ansible/ansiblePlayBook/work_everyday/jenkins/build_master/group_vars/build_vars.yml"
  with_items:
    - {export: "window2_peersID" , wallet: "{{ window2_peersID.stdout }}" }
    - {export: "window2_posterID" , wallet: "{{ window2_posterID.stdout }}" }
    - {export: "window2_link" , wallet: "{{ window2_link.stdout }}" }
  delegate_to: "{{ source }}"
  when: host == "window2"

- name: qiniu_up脚本下载
  shell: wget -O ~/bin/qiniu_up.py http://10.10.8.107/get/script_file/qiniu_up.py ; chmod +x ~/bin/qiniu_up.py
  when: host == "window2"

- name: 添加qiniu_up定时任务
  cron: 
    name: "qiniu_up"
    user: devnet
    minute: "*/60"
    job: "export FULLNODE_API_INFO\={{ fullnode2_link }} ; python3 ~/bin/qiniu_up.py --hour 24 >> ~/bin/qiniu_up.log"
  when: host == "window2"

- name: window2加入集群返回值
  debug: var=window2_result.stdout
  when: host == "window2"
